build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
        tests:
            environment:
                docker: true
            dependencies:
                override:
                    - true
                before:
                    - cp .env.scrutinizer .env.dev
                    - cp .env.scrutinizer .env.testing
                    - docker-compose up -d
                    - docker exec -it build_laravel_1 sudo pecl install xdebug-2.9.4
                    - docker exec -it build_laravel_1 docker-php-ext-enable xdebug
            project_setup:
                override:
                    - docker exec -it build_laravel_1 php artisan route:clear || echo ignore
                    - docker exec -it build_laravel_1 php artisan config:clear || echo ignore
                    - docker exec -it build_laravel_1 php artisan migrate --seed || echo ignore
            tests:
                override:
                    - command: './.scrutinizer.sh'
                      coverage:
                        file: 'coverage.clover'
                        format: 'clover'
checks:
    php:
        code_rating: true
        duplication: true

