language: php

php:
  - 7.4

services:
  - mysql

env:
  - TRAVIS_NODE_VERSION="10"
  global:
    - CC_TEST_REPORTER_ID=3a04751847584ea947348d575d284f58ce6de7b14a2b037498554c1091bea108
addons:
  apt:
    packages:
      - pyflakes
      - iverilog
      - arachne-pnr
      - arachne-pnr-chipdb
      - fpga-icestorm
      - fpga-icestorm-chipdb

before_script:
  - cp .env.travis .env
  - mysql -e 'create database hatchery_test;'
  - composer self-update
  - composer install --dev --no-interaction
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.2/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install stable
  - yarn
  - yarn production
  - yarn global add laravel-echo-server
  - php artisan key:generate
  - php artisan config:clear
  - curl -s -o zlib-1.2.11.tar.gz http://zlib.net/zlib-1.2.11.tar.gz
  - tar xvf zlib-1.2.11.tar.gz
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - cd zlib-1.2.11
  - ./configure
  - echo -e "#define MAX_WBITS  13\n$(cat zconf.h)" > zconf.h
  - make
  - export PATH=$PATH:`pwd`
  - cd ..
  - php artisan route:clear
  - php artisan config:clear
  - vendor/bin/phpstan analyse
  - vendor/bin/psalm
  - vendor/bin/phpunit

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - php vendor/bin/codacycoverage clover build/logs/clover.xml
  - cp build/logs/clover.xml coverage.xml
  - bash <(curl -s https://codecov.io/bash)
