name: Laravel feature testing and static analysis

on:
  push:
    branches: [master, develop, release/**, hotfix/**]
  pull_request:
    branches: [master, develop, release/**, hofix/**]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        php-versions: [ '7.3', '7.4', '8.0' ]

    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: imagick, xdebug
        ini-values: "post_max_size=256M"
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Execute tests (Unit and Feature tests) via Pest
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 33306
        DB_DATABASE: test
        DB_USERNAME: root
        DB_PASSWORD: password
      run: vendor/bin/pest
    - name: Static analysis with PHPStan
      run: vendor/bin/phpstan analyse
    - name: Static analysis with Psalm
      run: vendor/bin/psalm
